[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mmappet"
version = "0.2.0"
description = "Appendable, mmap-backed NumPy column storage"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
pandas = ["pandas"]
polars = ["polars"]
pyarrow = ["pyarrow"]
testing = ["pytest", "pandas"]

[project.scripts]
mmappet_show = "mmappet.scripts.mmappet_show:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
package-data = {"mmappet" = ["cpp/mmappet/*.h", "cpp/mmappet/*.hpp"]}
include-package-data = false

[tool.setuptools.package-dir]
"" = "src"
